# Generated by Django 4.2.4 on 2023-09-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joined',
            new_name='CustomUser_Date_Joined',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email',
            new_name='CustomUser_Email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='CustomUser_First_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='CustomUser_Last_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile_number',
            new_name='CustomUser_Mobile_Number',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='CustomUser_User_Name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='CustomUser_is_Staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='CustomUser_Dept',
            field=models.CharField(choices=[('CIV', 'Civil'), ('C&P', 'Contract & Procurement'), ('CHEM', 'Chemical'), ('ELE', 'Electrical'), ('F&A', 'Finance & Accounts'), ('F&S', 'Fire & Safety'), ('HR', 'Human & Resource Development'), ('INST', 'Instrumentation'), ('EMCH', 'Mechanical'), ('OPS', 'Operation'), ('O&M', 'Operation & Maintenance'), ('P/L', 'Pipeline')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='CustomUser_Designation',
            field=models.CharField(choices=[('S3', 'Assistant'), ('S4', 'Senior Assistant'), ('S5', 'Senior Assistant'), ('S6', 'Senior Assistant'), ('S7', 'Senior Assistant'), ('E0', 'Senior Assistant'), ('E1', 'Engineer'), ('E1', 'Officer'), ('E2', 'Senior Engineer'), ('E2', 'Senior Officer'), ('E3', 'Manager'), ('E4', 'Senior Manager'), ('E5', 'Chief Manager'), ('E6', 'Dy. General Manager'), ('E7', 'General Manager'), ('E8', 'Chief General Manager'), ('E9', 'Executive Director')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='CustomUser_is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
