# Generated by Django 4.2.4 on 2023-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_department_customuser_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_CPF', models.IntegerField(unique=True)),
                ('employee_First_name', models.CharField(max_length=20)),
                ('employee_Last_name', models.CharField(max_length=20)),
                ('employee_Dept', models.CharField(max_length=20)),
                ('employee_Designation', models.CharField(max_length=50)),
                ('employee_Email', models.EmailField(max_length=50, unique=True)),
                ('employee_HoD', models.BooleanField(default=False)),
                ('employee_Mob', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
